### ISSUE TITLE
update app to be consistent with NodeJs Immersive Curriculum 

### ISSUE THREAD

**Issue by nwalberts** [LaunchAcademy/generator-engage#120]
Note, for each item, I link to a relevant example in our staff group project app for reference! Just be aware that a file or two makes reference to "resource" which is one of the models in our app. 

- [x] Add `server/src/services/cleanUserInput` to base app, since this has always been provided to students
[Example](https://github.com/LaunchAcademy/coding-crossroads/blob/master/server/src/services/cleanUserInput.js) 
- ~~[ ] Ensure that any routes that employ `insert` or `update` check for validation error, and throw a 500 status code in the event an error is thrown that isn't a ValidationError~~
Example AND only file affected from the recent auth updates [usersRouter](https://github.com/LaunchAcademy/coding-crossroads/blob/master/server/src/routes/api/v1/usersRouter.js)
- [ ] Update all `.prettierrc` to match immersive conventions
[Example](https://github.com/LaunchAcademy/coding-crossroads/blob/master/.prettierrc)
- [x] Add Objection-unique to package.json, especially given students seem to break it every time they add it themselves
[Example & Version Number](https://github.com/LaunchAcademy/coding-crossroads/blob/master/server/package.json)
- [x] Update Api folder structure pattern in the Immersive curriculum by removing the `apiRouter.js` and `v1Router.js` files 
[Example](https://github.com/LaunchAcademy/coding-crossroads/blob/master/server/src/routes/rootRouter.js)
- [x] Add base seeder config to app. This actually matches interlock! 
this includes: updating the `server/package.json` for the `db:seed` script, adding a `Seeder.js` and adding a `seeders` folder in `server/src/db`
- [ ] Update `User` model jsonSchema validations to have uniqueness validation on email. Also consider adding `format: email` to the validation for the `email` property as well. We havent added this to the staff group project app yet, but its the same pattern used in interlock. [Uniqueness validation in curriculum](https://learn.launchacademy.com/teams/admins/curricula/on-campus-boston-31/lesson_groups/week_5:_react_express_monoliths_with_objection/lessons/model-level-validations-with-jsonSchema#uniqueness-validations) [documentation for format](https://json-schema.org/understanding-json-schema/reference/string.html#format)
- [x] Update `server/src/db/migrations.stub.cjs` to have async functions on `up` and `down`

# Issues that Dan may have resolved already: 

- [x] Update `TopBar` component's "Home" button to navigate to "/" rather than "/home"
[Example](https://github.com/LaunchAcademy/coding-crossroads/blob/master/client/src/components/layout/TopBar.js)
- [x] Update `SignOutButton` to fetch DELETE to the correct path
[Example](https://github.com/LaunchAcademy/coding-crossroads/blob/master/client/src/components/authentication/SignOutButton.js)

**Comment by bkincart** [comment]
Note that there is already a separate issue to add the seeding pattern :)

**Comment by dpickett** [comment]
@nwalberts can you create issues for the above three withstanding items (minus the seeding Brianna mentions is documented in #117 and close this ticket? thanks!

**Comment by bkincart** [comment]
I was in here so I just took care of this @nwalberts :)
