### ISSUE TITLE
unable manually navigate to a nested/dynamic path

### ISSUE THREAD

**Issue by ohad-porat** [LaunchAcademy/generator-engage#158]
when navigating to a nested path via URL or anchor tag such as `/characters/:characterId/edit` we end up getting an error of: `GET http://localhost:3000/new-character/dist/bundle.js net::ERR_ABORTED 404 (Not Found)`

**SOLUTION:**
In `client/public/index.html` changed 
```
<script src="/..dist/bundle.js"></script>
```
 to 
```
<script src="/dist/bundle.js"></script>
```

**Comment by nwalberts** [comment]
Resolved https://github.com/LaunchAcademy/generator-engage/pull/163
