### ISSUE TITLE
Eslint fixes

### ISSUE THREAD

**Issue by CassandraNewell** [LaunchAcademy/generator-engage#40]
Currently, `.eslintrc` is in the top-level dir, but the `package.json` files with eslint (and friends) are in the server/client directories. As a result, `.eslintrc` looks for plugins and modules in `./node_modules` but can't find them. 

I believe we should move formatters into a top-level package.json to keep things simple -- otherwise, we'd need to point `.eslint` at the filepath for each plugin's config file, and we'd need to choose whether to do so for the server or the client.

Also, we need to add `prettier` itself as a dependency

**Comment by dpickett** [comment]
yes. totally agree! We need a toplevel `app` generator that is composed with both the `client` and the `server`. This is kind of messy at present state as the introduction of the `client` is pretty new and raw.

Given they operate as separate repositories and they deal with different concerns (client vs. server) I do currently think both should have their own unique eslint and prettier configurations.
