### ISSUE TITLE
Replace deprecated req.secret

### ISSUE THREAD

**Issue by CassandraNewell** [LaunchAcademy/generator-engage#41]
```
express-session deprecated req.secret; provide secret option 
/server/src/middlewares/addExpressSession.js:7:5
```

**Comment by dpickett** [comment]
that's an environment variable you have to add in your `.env` - do you have a populated value for it?

**Comment by CassandraNewell** [comment]
🤦🏼‍♀️ based on the error message, I assumed it was a deprecation... apparently not. Closing this out.

https://github.com/expressjs/session/issues/116
