### ISSUE TITLE
Sequelize-CLI is not ESM-friendly

### ISSUE THREAD

**Issue by CassandraNewell** [LaunchAcademy/generator-engage#43]
The fix might be as simple as modifying the .sequelizerc file to look for a `.cjs` config file, but I haven't been able to get that to work yet

https://github.com/sequelize/cli/issues/861
https://stackoverflow.com/questions/62121277/using-sequelize-cli-in-node-14-with-type-module

**Comment by dpickett** [comment]
I feel pretty strongly that we should move to typeorm (documented in #46) so I am going to mark this as blocked while we consider that possibility.

**Comment by dpickett** [comment]
TypeORM was a giant fail on Vanilla ESM so we're moving to ObjectionJS. Closing this for now in sweet anticipation of nuking sequelize entirely.
