### ISSUE TITLE
Bug when trying to run `yarn run console`: missing file

### ISSUE THREAD

**Issue by bkincart** [LaunchAcademy/generator-engage#98]
When running `yarn run console`, `console.js` is attempting to import `server/src/models/index.js` but that file does not exists. It looks like `generators/server/index.js` just needs to be updated to copy this file after line 197, but wanted to have more context here before making the change

**Comment by dpickett** [comment]
actually, the intent here is to have `server/index.js` enumerate and export all model instances. The file is in the templates but I don't think I'm copying it in.
